const ChatEventEnum = Object({
  CONNECTED_EVENT: 'connected',
  DISCONNECT_EVENT: 'disconnect',
  JOIN_CHAT_EVENT: 'joinChat',
  LEAVE_CHAT_EVENT: 'leaveChat',
  UPDATE_GROUP_NAME: 'updateGroupName',
  MESSAGE_RECIVED_EVENT: 'messageRecieved',
  NOTIFY_USERS_EVENT: 'notifyUsers',
  MESSAGE_UNDO_EVENT: 'messageUndo',
  NEW_CHAT_EVENT: 'newChat',
  SOCKET_EVENT_ERROR: 'socketError',
  STOP_TYPING_EVENT: 'stopTyping',
  TYPING_EVENT: 'typing',
  MESSAGE_DELETE_EVENT: 'messageDeleted',
  SOCKET_ERROR_EVENT: 'socketError',

  REQUEST_VIDEO_CALL: 'requestVideoCall',
  REJECT_VIDEO_CALL: 'rejectVideoCall',
  ACCEPT_VIDEO_CALL: 'acceptVideoCall',
  CLOSE_VIDEO_CALL: 'closeVideoCall',
  REQUEST_AUDIO_CALL: 'requestAudioCall',
  ACCEPT_AUDIO_CALL: 'acceptAudioCall',
  REJECT_AUDIO_CALL: 'rejectAudioCall',
  CLOSE_AUDIO_CALL: 'closeAudioCall',
});

const chatEventEnumNew = {
  JOIN_ROOM: 'joinRoom',
  ONLINE_EVENT: 'is_online',
  OFFLINE_EVENT: 'offline',
  APPROACHED_TALK: 'apprached_to_talk',
  NEW_GROUP_CHAT: 'created_room',
  KICKED_OUT_MEMBER: 'cickout_member',
  KICKED_OUT_YOU: 'you_member',
  NEW_MESSAGE: 'message',
  DELETED_MESSAGE: 'deleted_message',
  TYPING_ON: 'typing_on',
  TYPING_OFF: 'typing_off',
  MARK_READ: 'mark_read',
  MARKED: 'marked_read',
  SENDING_MEDIA: 'sending_media',
  SENT_MEDIA: 'sent_media',
  REQUEST_VIDEO_CALL: 'request_video_call',
  INCOMING_VIDEO_CALL: 'incoming_video_call',
  CANCELLED_VIDEO_CALL: 'cancelled_video_call',
  REJECT_VIDEO_CALL: 'reject_video_call',
  REJECTED_VIDEO_CALL: 'rejected_video_call',
  ANSWER_VIDEO_CALL: 'answer_video_call',
  CREATE_WEB_RTC_TRANSPORT: 'createWebRtcTransport',
  TRANSPORT_CONNECT: 'transport_connect',
  TRANSPORT_PRODUCE: 'transprt_produce',
  TRANSPORT_RECIVER_CONNECT: 'transport_recv_connect',
  CONSUME: 'consume',
  ON_CONSUMER_RESUME: 'on_consumer_resume',
  ACCEPTED_VIDEO_CALL: 'accepted_video_call',
  OFFLINE_CALLER: 'offline_caller',
  REQUEST_VIDEO_ROOM_TEST: 'request_video_call_test',
  INCOMING_VIDEO_ROOM_TEST: 'incoming_video_call_test',
  JOIN_VIDEO_ROOM_TEST: 'join_video_test',
  JOINED_VIDEO_ROOM_TEST: 'joinee_video_test',
};

const LoadLimits = Object.freeze({
  CONTACT_LIMIT: 50,
  CHAT_LIMIT: 100,
});

module.exports = { ChatEventEnum, chatEventEnumNew, LoadLimits };
